# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Prospect Agent - Build and deploy Python app to Azure Container Instances

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Build and push image"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build -f docker/dockerfile . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/python_agent:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/python_agent:${{ github.sha }}
    

      - name: "Deploy to Azure Container App"
        run: |
          az containerapp update \
            --name ${{ secrets.CONTAINER_APP_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --container-name ${{ secrets.CONTAINER_APP_NAME }} \
            --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/python_agent:${{ github.sha }}
